config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "cvs#index"
  resources :cvs do
    member do
      delete :destroy_avatar
    end
    resources :content_blocks, only: :create do
      collection do
        patch :change_position
      end
    end
  end
  resources :documents, only: %i[ create update destroy ]
  resources :paragraphs, only: %i[ create update destroy ]
  resources :images, only: %i[ create update destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/content_block.rb
class ContentBlock < ApplicationRecord
  belongs_to :cv
  belongs_to :content, polymorphic: true

  default_scope { order(position: :asc) }
end

# == Schema Information
#
# Table name: content_blocks
#
#  id           :bigint           not null, primary key
#  cv_id        :bigint           not null
#  position     :integer
#  content_type :string
#  content_id   :bigint
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

app/models/cv.rb
class Cv < ApplicationRecord
  has_many :content_blocks, dependent: :destroy
  belongs_to :user
  has_one_attached :avatar
  broadcasts_refreshes

  validates :avatar, content_type: {
    in: /\Aimage\/.*\z/,
    message: 'Неподдерживаемый формат картинки. Поддерживаемые форматы: png, jpeg, jpg, svg'
  }
end

# == Schema Information
#
# Table name: cvs
#
#  id         :bigint           not null, primary key
#  name       :string
#  surname    :string
#  patronymic :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#

app/models/document.rb
class Document < ApplicationRecord
  has_one :content_block, as: :content, dependent: :destroy
  has_one_attached :file

  after_update :set_filename

  def set_filename
    original_extension = self.file.blob.filename.to_s.split('.').last
    self.file.blob.update(filename: "#{self.file_name}.#{original_extension}") if file.attached? && self.file_name.present?
  end
end

# == Schema Information
#
# Table name: documents
#
#  id         :bigint           not null, primary key
#  file_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/image.rb
class Image < ApplicationRecord
  has_one :content_block, as: :content, dependent: :destroy
  has_one_attached :file

  validates :file, content_type: {
    in: /\Aimage\/.*\z/,
    message: 'Invalid image format. Available formats: png, jpeg, jpg, svg'
  }
end

# == Schema Information
#
# Table name: images
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/paragraph.rb
class Paragraph < ApplicationRecord
  has_one :content_block, as: :content, dependent: :destroy
end

# == Schema Information
#
# Table name: paragraphs
#
#  id         :bigint           not null, primary key
#  text       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cvs

end

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def render_alert(model)
    flash.now[:alert] = model.errors.messages.values.join("\n")
    render turbo_stream: turbo_stream.update(
      "#{model.class.to_s.downcase}-#{model.id}-alert",
      partial: "alert",
      locals: { model: model}
    )
  end
end

app/controllers/content_blocks_controller.rb
class ContentBlocksController < ApplicationController
  def create
    ActiveRecord::Base.transaction do
      content = params[:content_block][:content_type].constantize.create!
      @content_block = ContentBlock.create!(content_block_params.merge(content_id: content.id))
    end
    redirect_to @content_block.cv
  end

  def change_position
    params[:content_blocks].each do |content_block|
      next if content_block[:id].blank?
      ContentBlock.find(content_block[:id]).update_attribute(:position, content_block[:position])
    end
  end

  private
    def content_block_params
      params.require(:content_block).permit(:cv_id, :position, :hidden, :content_type, :content_id)
    end
end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
  before_action :set_cv, only: %i[show edit update destroy destroy_avatar]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @cvs = Cv.all
  end

  def show
    @content_block = @cv.content_blocks.build
  end

  def new
    @cv = Cv.new
  end

  def create
    @cv = Cv.new(cv_params.merge(user: current_user))

    if @cv.save
      redirect_to @cv, notice: "Cv was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    if @cv.update(cv_params)
      redirect_to @cv, notice: "Cv was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy_avatar
    @cv.avatar.purge
    redirect_to @cv
  end

  def destroy
    @cv.destroy
    redirect_to cvs_url, notice: "Cv was successfully destroyed.", status: :see_other
  end

  private

    def set_cv
      @cv = Cv.find(params[:id])
    end

    def cv_params
      params.require(:cv).permit(:name, :surname, :patronymic, :avatar, :user_id)
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ update destroy ]

  def update
    if @document.update(document_params)
      redirect_to @document.content_block.cv
    else
      render_alert(@document)
    end
  end

  def destroy
    @document.destroy
    redirect_to @document.content_block.cv
  end

  private
    def set_document
      @document = Document.find(params[:id])
    end

    def document_params
      params.require(:document).permit(:content_block_id, :file, :file_name)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ update destroy ]

  def update
    if @image.update(image_params)
      redirect_to @image.content_block.cv
    else
      render_alert(@image)
    end
  end

  def destroy
    @image.destroy
    redirect_to @document.content_block.cv
  end

  private
    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:content_block_id, :file, :description)
    end
end

app/controllers/paragraphs_controller.rb
class ParagraphsController < ApplicationController
  before_action :set_paragraph, only: %i[ update destroy ]

  def update
    if @paragraph.update(paragraph_params)
      redirect_to @paragraph.content_block.cv
    else
      render_alert(@paragraph)
    end
  end

  def destroy
    @paragraph.destroy
    redirect_to @paragraph.content_block.cv
  end

  private
    def set_paragraph
      @paragraph = Paragraph.find(params[:id])
    end

    def paragraph_params
      params.require(:paragraph).permit(:content_block_id, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cvs_helper.rb
module CvsHelper
  def author?
    current_user.present? && current_user.id == @cv.user_id
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/application/_alert.html.erb
<div
  class="alert alert__<%= model.class.to_s.downcase %>"
  id="<%= model.class.to_s.downcase %>-<%= model.id %>-alert"
>
  <%= flash[:alert] %>
</div>

app/views/application/_footer.html.erb
<div class='footer'>
  <div class='container'>
    <small class="copyright">
      Copyright Mulenok Ivan
    </small>
  </div>
</div>

app/views/application/_nav.html.erb
<nav class="nav">
  <div class="nav__outer">
    <div class="container">
      <ul class="nav__list nav__list--between">
        <li class="nav__item">
          <%= link_to 'Home',
            root_path,
            class: 'nav__link ' + (current_page?(root_path) || current_page?(cvs_path) ? 'nav__link--active' : '')
          %>
        </li>
        <li class="nav__item nav__item--auth">
          <%= current_user ?
            (button_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav__link')
            :
            (link_to 'Sign in', new_user_session_path, class: 'nav__link')
          %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/cvs/_cv.html.erb
<div class="cv">
  <div class="card">
    <div class="avatar">
      <% if cv.avatar.present? %>
        <div
          style="background-image: url(<%= rails_blob_url(cv.avatar) %>)"
          class="avatar__image"
        >
        <%= link_to '', destroy_avatar_cv_path(@cv), class: 'avatar__delete icon icon--delete',
            data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } if author? %>
        </div>
      <% else %>
        <div class="avatar__image avatar__image--default">
          <% if author? %>
            <%= simple_form_for cv, html: { class: "avatar__form" } do |form| %>
              <span class="input input--file">
                <label class="input__label">
                  Загрузить изображение
                </label>
                <%= form.file_field :avatar,
                  class: 'input__field',
                  onchange: "this.form.submit()"
                %>
              </span>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="card__info">
    <%= simple_form_for cv, data: { controller: 'toggle-visible' } do |form| %>
      <div class="js-toggle-visible">
        <%= cv.surname&.capitalize %>
        <%= cv.name&.capitalize %>
        <%= cv.patronymic&.capitalize %>
        <% if author? %>
          <span class="icon icon--edit" data-action="click->toggle-visible#onShowContent"></span>
        <% end %>
      </div>
      <div class="js-toggle-visible-content js-hidden">
        <div class="form form__group form__group--inline ">
          <%= form.input :surname, label: false, :input_html => {:class => 'input input__field--with-background'}%>
          <%= form.input :name, label: false, :input_html => {:class => 'input input__field--with-background'} %>
          <%= form.input :patronymic, label: false, :input_html => {:class => 'input input__field--with-background'} %>
        </div>

        <button data-action="click->toggle-visible#onHideContent" type="button" class="btn btn--primary">Close</button>
        <%= form.button :submit, 'Save', class: 'btn btn--primary' %>
      </div>
    <% end %>
    </div>
    <% if author? %>
      <div class="card__actions card__actions--right-between">
        <%= link_to 'Delete Cv', cv_path(cv), class: 'btn btn--danger',
          data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  </div>

  <div data-controller="sortable" data-cv-id="<%= @cv.id %>">
    <% @cv.content_blocks.order(position: :asc).each do |content_block| %>
      <div class="content-block <%= 'content-block--edit' if author? %> js-content-block" data-id="<%= content_block.id %>">
        <% if author? %>
          <div class="content-block__actions content-block__actions--paragraph">
            <span class="js-sortable-handle"></span>
            <%= link_to '', polymorphic_path(content_block.content), class: 'icon icon--delete',
              data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
          </div>
        <% end %>
        <%= render content_block.content %>
      </div>
    <% end %>
  </div>

  <% if author? %>
    <div class="fixed-menu" data-controller="fixed-menu">
      <button class="icon icon--plus icon--lg" data-action="click->fixed-menu#openMenu"></button>
      <div class="fixed-menu__inner">
        <h2> Content blocks list </h2>
        <ul class="list">
          <% %w(Paragraph Image Document).each do |content_type| %>
            <li class="list__item content-type">
              <%= simple_form_for [@cv, @content_block] do |form| %>
                <div class="content-type__img">
                  <%= image_tag "content_types/#{content_type.downcase}.svg", class: 'content-type__image' rescue nil %>
                </div>
                <div class="content-type__content">
                  <%= form.hidden_field :content_type, value: "#{content_type}" %>
                  <%= form.hidden_field :cv_id, value: @cv.id %>
                  <%= form.submit "Add #{content_type}", class: 'btn btn--primary' %>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/cvs/_cv_list.html.erb
<% @cvs.each do |cv| %>
  <li class="list__item card">
    <% if cv.avatar.present? %>
      <div style="background-image: url(<%= rails_blob_url(cv.avatar) %>)"
        class="avatar__image avatar__image--sm"
      >
      </div>
    <% else %>
      <div class="avatar__image avatar__image--default avatar__image--sm">
      </div>
    <% end %>
    <div class="card__info">
      <p class="card__fullname">
        <%= cv.surname&.capitalize %>
        <%= cv.name&.capitalize %>
        <%= cv.patronymic&.capitalize %>
      </p>
    </div>
    <div class="card__actions">
      <%= link_to cv_path(cv), class: 'btn btn--primary' do %>
        <span>Show</span>
        <span class="icon icon--link"></span>
      <% end %>
    </div>
  </li>
<% end %>

app/views/cvs/_form.html.erb
<%= simple_form_for @cv , html: {:class => 'form'} do |form| %>
  <% if @cv.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(formabc.errors.count, "error") %> prohibited this cv from being saved:</h2>

      <ul>
        <% @cv.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block", :class => 'input__label'%>
    <%= form.text_field :name , :class => 'input__field--text' %>
  </div>

  <div>
    <%= form.label :surname, style: "display: block", :class => 'input__label'  %>
    <%= form.text_field :surname, :class => 'input__field--text' %>
  </div>

  <div>
    <%= form.label :patrnymic, style: "display: block", :class => 'input__label' %>
    <%= form.text_field :patronymic, :class => 'input__field--text' %>
  </div>

  <div class="form form__group form__group--inline">
    <div>
      <%= form.submit 'Save', :class => 'btn btn--primary'%>
    </div>

    <div>
      <%= link_to "Cancel", :back, :class => 'btn btn--danger' %>
    </div>
  </div>

<% end %>

app/views/cvs/edit.html.erb
<h1>Editing cv</h1>

<%= render "form", cv: @cv %>

<br>

<div>
  <%= link_to "Show this cv", @cv %> |
  <%= link_to "Back to cvs", cvs_path %>
</div>

app/views/cvs/index.html.erb
<%= render 'cv_list' %>

<%= link_to 'New Cv', new_cv_path, class: 'btn btn--primary' %>

app/views/cvs/new.html.erb
<h1>New form</h1>

<%= render "form", form: @form %>

<br>

app/views/cvs/show.html.erb
<%= turbo_stream_from @cv %>

<%= render @cv %>

app/views/documents/_document.html.erb
<div class="document">
  <% if document.file.blob.present? %>
    <span class="document__link">
      <span class="document__icon file-icon file-icon--<%= document.file.blob.filename.to_s.split('.').last %>"></span>
      <%= link_to document.file.blob.filename, rails_blob_path(document.file, discposition: 'inline') %>
    </span>
  <% else %>
    <%= simple_form_for document do |form| %>
      <div
        class="input-file"
        data-controller="input-file"
      >
        <%= form.input :file_name,
          :input_html => { :class => 'input-file__file-name input__field input__field--text' },
          :label_html => { :class => "input__label" },
          label: 'Filename',
          placeholder: 'Enter filename' %>
        <div>
          <span class="input-file__btn btn btn--primary">
            <span class="input-file__placeholder">
              Choose file
            </span>
            <%= form.file_field :file, :class => 'input-file__field js-input-file' %>
          </span>
          <span class="input-file__file js-input-file--span js-hidden">
            Current file:
          </span>
        </div>
        <%= form.submit 'Save', class: 'input-file__save btn btn--primary' %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/images/_image.html.erb
<% if image.file.present? %>
  <div class="image">
    <%= image_tag image.file, class: 'image__file' %>
  </div>
<% else %>
  <%= simple_form_for image do |form| %>
    <div
      class="input-file"
      data-controller="input-file"
    >
      <div>
        <span class="input-file__btn btn btn--primary">
          <span class="input-file__placeholder">
            Choose file
          </span>
          <%= form.file_field :file, :class => 'input-file__field js-input-file' %>
        </span>
        <span class="input-file__file js-input-file--span js-hidden">
          Current file:
        </span>
      </div>
      <%= render partial: 'alert', locals: {model: image} %>
      <%= form.submit 'Save', class: 'input-file__save btn btn--primary' %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fortis</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="turbo-refresh-method" content="morph">
    <meta name="turbo-refresh-scroll" content="preserve">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", media: "all" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'nav' %>
    <main>
      <div class='container'>
        <%= yield %>
      </div>
    </main>
    <%= render 'footer' %>
  </body>
</html>

app/views/paragraphs/_paragraph.html.erb
<div class="paragraph">
  <%= simple_form_for paragraph, data: { controller: 'toggle-visible' } do |form| %>
    <div class="paragraph__content js-toggle-visible">
      <div data-action="click->toggle-visible#onShowContent">
        <% if paragraph.text.present? %>
          <%= paragraph.text %>
        <% else %>
          Click to add content
        <% end %>
      </div>
    </div>

    <div class="js-toggle-visible-content js-hidden">
      <div>
        <%= form.text_area :text, class: 'input-textarea', placeholder: 'Enter text...' %>
      </div>
      <div>
        <%= form.submit 'Save', class: 'btn btn--primary' %>
        <button type="button" class="cancel btn btn btn--primary" data-action="click->toggle-visible#onHideContent">Cancel</button>
      </div>
    </div>
  <% end %>
</div>